- name: Wait for Scylla port
  wait_for:
    port: 9042
    delay: 20
    timeout: 300

- name: Ensure CQL is ready
  shell: cqlsh {{ scylla_listen_address }} -e "DESCRIBE KEYSPACES"
  register: result
  retries: 10
  delay: 10
  until: result.rc == 0
  changed_when: false
